---
- hosts: all
  tasks:
    - group_by: key={{item}}
      with_lines:
        - cat /etc/ansible/groups
    - group_by: key=runtime
      tags: [ runtime ]

- hosts: cleopatra
  sudo: true
  roles: 
    - hypervisor
    - docker-host

- hosts: docker-base
  roles: 
    - docker-base
    - self-updater

- hosts: ceph-osd
  roles:
    - ceph
