---
 - name: update apt cache
   apt: update_cache=yes cache_valid_time=3600

 - name: ensure apt prereqs
   apt: pkg="python-pycurl"

 - name: add docker apt key
   apt_key: url="http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x36A1D7869245C8950F966E92D8576A8BA88D21E9" id="A88D21E9"

 - name: add docker repo
   apt_repository: repo="deb http://get.docker.io/ubuntu docker main" update_cache=no

 - name: install docker
   apt: pkg="lxc-docker=0.7.6"
