---
- name: download supervisor
  git: repo={{ supervisor_repo }} dest="/root/supervisor" version={{ supervisor_version }}

- name: install setuptools-git
  apt: pkg=python-setuptools-git update_cache=yes cache_valid_time=3600

- name: install supervisor
  command: /usr/bin/python2  /root/supervisor/setup.py install creates=/usr/local/bin/supervisord 

- name: install supervisord conf
  copy: src=supervisord.conf dest=/etc/supervisord.conf mode=0600 owner=root group=root

- name: create supervisord.d directory
  file: path=/etc/supervisord.d state=directory mode=0700 owner=root group=root

- name: create run command
  copy: src=run.sh dest=/root/run.sh mode=0700 owner=root group=root
